# Generated by Django 3.1.7 on 2021-04-01 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tip_data', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tip',
            old_name='url_title',
            new_name='urlTitle',
        ),
    ]
